services:
  - type: web
    name: ctf-webapp
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    healthCheckPath: /
    autoDeploy: true 